os:
- linux
services:
- docker
language: node_js
node_js:
- 8.9.4
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=8.9.4
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - secure: UFWMko62Hf2El0uo7AiEwzKqCTuW8Un7eBuCfj1/BvLBPRNgZXNXs5ApfxW5KMJgaG5F46e+R+WqhP8JsS+YUYcfPAs4t603kAuyE75L1Q+a1iqV2t1NB5Or1XZNc4JnKKE8Pxw7dGq5AD1eHeTeOIu4IQtYUNpt8q/RrcAl/QR5BvI7h7/4db93pskF+3JQjDXGH5HORkgx0bSps8Lrp3NJf2eBOR0fDaGQ8k4Uxt8D3hJ5udJ5m1VYXKl7jgJrKmdFqDV9VFgCMuc9rY7giTX/zeFCKf+xxn8nMhVPJZhlzR0GhKSAP4ToYYK0RcMRdAJ2bA+BISqYfgni9ZScI1vhlzhuWWQbigP0nEEsec6sCEFbH/SsFcDVtZ3zAS3CWVorlg1GWZbNm2NtF4Xu/AwBI3rLOERQtnViKqk+BJg3XpZHbzl8xCU2MRSzvEvbtxXU5L4e4aGKwolMb2xT3QcW0Z8oa/VgwWYFdindTSEdzbMEkjXeCxMwwGoLJQTRAxP1PvY4c4Z0Sxyy6lFVvStVNiT2mgdzsPDoMjUgVtFitxTEPmtHhkCu9TYE4BLWQEEI5jDT8jbOjqeudrJOOb3UNAvNnCXLVqGtru3YDeW1UNUMW9BoMtIxMBZZoEWN89htkcxxkBmt79q2zO8mLfJFCGGvTNRSCU7afo56hsc=
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x mvnw
- "./mvnw clean test"
- yarn test
- "./mvnw verify -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: openshift
  user: antoniohgarcia
  password:
    secure: gMNviaS23J9oj6GHnzxqVr5/vwEKmuFRPZXScOshLDzypajPEF8V2f5k3utuzjKu5gK8PK/D+diB5JZFdFNYp1JEWutVW8vHw2yz0K/y7ihma4aBdIwIrtkkWji7WO1sm/d60spMqEOe8b5Y0H77pQYm0AMPMKKQ2QDNXDLQ27WAAyjUxzqST7A1GHbNb/I+ZK5keAqFKXTsWow/B3P+QM/+SvrR8ZBua+2589s26/w1SHWv7TXVtYdwZXu+bzGTMdPiopEx+WUHO+DBah+vfpSQka6gW6rEMthldQRrn/sbqSq3j6Thx3uUf7KCgTScM6owvPiWrciue48xxw9twLT8pzpNTyLtIizlnWq3ufBfWeIZDnRQYeCINIRxxYGEtXFIjZAt7JjWqXVw2iaXYjLEKd/oIBZ+9Jh4Q+HrzsLp3onPXK96qMM2NMFYGvy+lhwHJ/0w5kR09ErpKdR8xfYgLEAXKLNPpoOgRxiX/6XSasc69nE6I+IrXEOuhe0mM0NEPoRq1ZHxnPxbwowiDZcrZccv1+anesolfEeB24SBYqQ1JV7tGjNNr9AjLskeyECV4s2CJVg726o60sK+XD7ukV6RRpYQpm0QuLnnb/6md5IRT3A8/vyaqaddJZXd/+juXT+qM8J5M/hOWzop7w5DLlhPWYCDRDEMkD5JS+4=
  app: SampleApplication
  domain: ''
  on:
    repo: antoniohgarcia/SampleApplication
